### ISSUE TITLE
[NEED ASSIST] Cancelling purchase in redirect flows

### ISSUE THREAD

**Issue by Natelegreat1** [Adyen/adyen-ios#1253]
### Problem 
When a User selects a redirect payment method (example: Klarna or iDEAL) from the Drop-In component, a web view is presented for them to continue their transaction. 
At that point in time, a purchase has already begun and is in progress.
If the User presses any sort of "Cancel" button within the web view, the purchase is cancelled and our UI can react accordingly (by dismissing the Adyen Drop-In). However, if the User selects the "Cancel" in the SFSafariViewController or drags to dismiss, it appears that Adyen is not notified of the fact and the purchase remains idle until it eventually times out.

Drop-in | Supported Webview exit | Unsupported Webview exit
-- | -- | --
<img width="200" alt="Screenshot 2023-06-22 at 14 38 06" src="https://github.com/Adyen/adyen-ios/assets/2666640/898fdf9d-047d-44c2-b19b-09e0b25ef799"> | <img width="200" src=https://github.com/Adyen/adyen-ios/assets/2666640/0cd58ec8-3ac2-4f1d-897a-2e4fa8301ac3> | <img width="200" src=https://github.com/Adyen/adyen-ios/assets/2666640/76f19427-5cf5-4b3a-9162-08f2b7a985eb>

1. Select a redirect payment method (ex. Klarna)
2. Close the SFSafariViewController or drag to dismiss
3. Note that the purchase has not been cancelled, meaning that it is continuously waiting for the User to resume their payment

### Challenge
Is there a way for an iOS client to notify Adyen that a User has dropped the purchase (whether "Cancel" button, opening in Safari, dragging to dismiss, etc) so that our backend can cancel the purchase on our end? Should this be happening automatically by the SDK and we just need to enable something?

I have found mention [here](https://github.com/Adyen/adyen-ios/pull/277) of how to detect the User has closed the view but it's unclear if the delegate is also informing Adyen of the cancel.

Bonus: We would like to be able to distinguish whether the purchase was cancelled by the User and not by Adyen (due to a payment issue) so we can avoid sending the User a "something went wrong" email.

**Comment by descorp** [comment]
Hey @Natelegreat1 

It is not possible on sessions, but for ["Advanced flow"](https://docs.adyen.com/online-payments/build-your-integration/additional-use-cases/advanced-flow-integration) one can use [DropInComponentDelegate.didCancel](https://github.com/Adyen/adyen-ios/blob/ac2fa601d2136cf9948dac4a7f612a92a599d968/Adyen/Core/Core%20Protocols/DropInComponentDelegate.swift#L73).

:warning: Event `didCancel` will notify you in case the shopper stopped the payment, but it **does not terminate the transaction**, hanse it is still possible that it could be completed by the shopper: for example, if it was opened in a browser.

**Comment by Natelegreat1** [comment]
Thanks for getting back to me @descorp.
> ⚠️ Event `didCancel` will notify you in case the shopper stopped the payment, but it **does not terminate the transaction**, hanse it is still possible that it could be completed by the shopper: for example, if it was opened in a browser.

We are using various `DropInComponentDelegate` functions already (`didSubmit`, `didComplete`, etc), but I am unable to figure out how to get `didCancel` to be triggered by the DropIn. None of the "Cancel" CTAs in my above screenshots (Drop-in X, webview nav bar 'Cancel', webview content 'Cancel') seem to trigger it. The other delegate functions all work as expected. Is there more required than `dropIn.delegate = self`?

**Comment by descorp** [comment]
Hey @Natelegreat1 

Indeed, there is a bug on our side. `didCancel` never called.

**UPD**

PR for this: #1258

**Comment by cdnbacon** [comment]
Thanks @descorp. I see it hasn't been merged yet after a month. Has the decision to move forward with the fix changed? 

If not, when should we expect this to get a formal release, and under which version(s) branch (v4, v5) would you plan on releasing it?

**Comment by descorp** [comment]
Sorry for postponing this, @cdnbacon 

we have CI issue that is blocking us to merge it.
Fix going to be done on v5

**Comment by Swaxer** [comment]
Hey @descorp, can't see that this was included in v5. Looks like #1258 would solve it but it's not merged yet. Any updates on this? We're left in a bad state when a user cancels the payment and we can't tell that it has been cancelled.

**Comment by xpereta** [comment]
We are also experiencing this bug.

@descorp It's been a while. Is there a recommended workaround or mitigation while we wait for #1258 to be included in a future release?

Thanks!

**Comment by vladyslav-petruk-photobox** [comment]
@descorp @goergisn Do you have any updates on this one?

**Comment by descorp** [comment]
Fix was merged in #1392

**Comment by vladyslav-petruk-photobox** [comment]
@descorp Thanks! I tested this on 5.4.0 release and it seems like it's not fixed. Could you please confirm? 
cc @goergisn

**Comment by descorp** [comment]
Hey @vladyslav-petruk-photobox 

I just verified it locally.
[DropInComponentDelegate.didCancel](https://github.com/Adyen/adyen-ios/blob/ac2fa601d2136cf9948dac4a7f612a92a599d968/Adyen/Core/Core%20Protocols/DropInComponentDelegate.swift#L73) will be only called when payment was initiated (e.g. after didSubmit was called).

**Comment by vladyslav-petruk-photobox** [comment]
@Natelegreat1 @cdnbacon @Swaxer Could you please confirm if it's working for you on the latest 5.4.0 Adyen?

**Comment by Swaxer** [comment]
@vladyslav-petruk-photobox It works for us!

**Comment by descorp** [comment]
Thanks for confirming @Swaxer 

I am going to close this ticket.
@vladyslav-petruk-photobox feel free to continue here if you need any additional help or create a new ticket if you face an issue

**Comment by Natelegreat1** [comment]
> @Natelegreat1 @cdnbacon @Swaxer Could you please confirm if it's working for you on the latest 5.4.0 Adyen?

I can confirm that `didCancel` delegate is now working on 5.4.0.
