### ISSUE TITLE
Support library evolution

### ISSUE THREAD

**Issue by ffittschen** [Adyen/adyen-ios#1354]
**Describe the bug**
As we are using Adyen alongside an internal binary framework, we need to compile it with library evolution enabled (`BUILD_LIBRARY_FOR_DISTRIBUTION=YES`), so that binary compatibility between our binary framework and its Adyen dependencies is guaranteed.

Starting with [this PR](https://github.com/Adyen/adyen-ios/pull/895), Adyen uses the underscored attribute `@_spi` to mark declarations as System Programming Interface (SPI). These `@_spi` annotations cause build errors when compiling Adyen with the `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` build setting to enable library evolution.

**To Reproduce**
1. Check out this repository
2. Run the following command

```bash
xcodebuild -project Adyen.xcodeproj -scheme Adyen -destination 'generic/platform=iOS' -archivePath "archives/Adyen-iphoneos.xcarchive" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES clean archive
```

**Expected behavior**
I'd expect no build errors when using the `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` build setting.

**Screenshots**

**Environment**
 - Device: n/a
 - iOS Version: n/a
 - SDK Version: n/a
 - Adyen API Version: n/a
 - Package management system: n/a
 - Xcode version: n/a
 - Mac OS type: n/a

**Additional context**
This problem was first brought up in this issue: https://github.com/Adyen/adyen-ios/issues/1130

**Comment by descorp** [comment]
Hey @ffittschen 

Thank you for your feedback!
We have noticed this behavior lately but didn't have any research on this topic yet.
We will keep you posted.

**Comment by descorp** [comment]
Hey @ffittschen 

We would like to have a better understanding of your case.
The "internal binary framework", who uses it?

**Comment by descorp** [comment]
Prospect PR #1413

**Comment by goergisn** [comment]
Hi @ffittschen,

We merged a fix for the described issue to develop yesterday 🤝 
Feel free to check it out for confirmation for now.

Best,
Alex

**Comment by goergisn** [comment]
Hi @ffittschen,

we just released [5.5.0](https://github.com/Adyen/adyen-ios/releases/tag/5.5.0) that contains support for library evolution.

Please let us know if you are running into any issues.
And feel free to re-open the issue, if so. 👍 

Best,
Alex

**Comment by ffittschen** [comment]
Hi @goergisn, while trying to update to 5.5.0, we are still facing an issue with Adyen's `@_spi` usage. Compiling the individual Adyen schemes with library evolution enabled and creating an xcframework out of them works fine now, but when importing them in our own code, we get the following error.

> Cannot use conformance of 'AbstractPersonalinformationComponent' to 'Component' here; the conformance is declared as SPI

![Adyen_library_evolution](https://github.com/Adyen/adyen-ios/assets/7734806/77482cab-0755-4768-8312-01df95639d02)

Attached below you can find a minimal sample project that reproduces the issue. For the example, I compiled `Adyen` and its dependency `AdyenNetworking` and created XCFrameworks using the following script:

<details>

<summary>archive.sh</summary>

```bash
#!/usr/bin/env bash
set -e

WORKING_DIR=$(pwd)
BUILD_PRODUCTS_DIRECTORY="archives"
PROJECT_NAME="Adyen.xcodeproj"
SCHEME_NAME="$1"
FRAMEWORK_PATH="${WORKING_DIR}/${BUILD_PRODUCTS_DIRECTORY}/${SCHEME_NAME}.xcframework"
SIMULATOR_ARCHIVE_PATH="${WORKING_DIR}/${BUILD_PRODUCTS_DIRECTORY}/${SCHEME_NAME}-iphonesimulator.xcarchive"
IOS_DEVICE_ARCHIVE_PATH="${WORKING_DIR}/${BUILD_PRODUCTS_DIRECTORY}/${SCHEME_NAME}-iphoneos.xcarchive"
DERIVED_DATA_PATH="${WORKING_DIR}/DerivedData"

mkdir -p "${BUILD_PRODUCTS_DIRECTORY}"
echo "Created ${BUILD_PRODUCTS_DIRECTORY}"
echo "Archiving ${SCHEME_NAME}"

set -o pipefail && xcodebuild -project "${PROJECT_NAME}" -scheme "${SCHEME_NAME}" -destination 'generic/platform=iOS' -archivePath "${IOS_DEVICE_ARCHIVE_PATH}" -derivedDataPath "${DERIVED_DATA_PATH}" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGNING_ALLOWED="NO" clean archive | tee "${WORKING_DIR}/${BUILD_PRODUCTS_DIRECTORY}/${SCHEME_NAME}-iphoneos.log" | xcbeautify
set -o pipefail && xcodebuild -project "${PROJECT_NAME}" -scheme "${SCHEME_NAME}" -destination 'generic/platform=iOS Simulator' -archivePath "${SIMULATOR_ARCHIVE_PATH}" -derivedDataPath "${DERIVED_DATA_PATH}" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGNING_ALLOWED="NO" clean archive | tee "${WORKING_DIR}/${BUILD_PRODUCTS_DIRECTORY}/${SCHEME_NAME}-iphonesimulator.log" | xcbeautify

set -o pipefail && xcodebuild -create-xcframework \
    -framework "${SIMULATOR_ARCHIVE_PATH}/Products/Library/Frameworks/${SCHEME_NAME}.framework" \
    -debug-symbols "${SIMULATOR_ARCHIVE_PATH}/dSYMs/${SCHEME_NAME}.framework.dSYM" \
    -framework "${IOS_DEVICE_ARCHIVE_PATH}/Products/Library/Frameworks/${SCHEME_NAME}.framework" \
    -debug-symbols "${IOS_DEVICE_ARCHIVE_PATH}/dSYMs/${SCHEME_NAME}.framework.dSYM" \
    -output "${FRAMEWORK_PATH}"
```

</details>

After creating the XCFrameworks, I generated the project using [Tuist](https://github.com/tuist/tuist) (which should not be relevant for the example, but I included the Project.swift for completeness) and built the `LibraryEvolutionTest` scheme, which results in the same error as in the screenshot above.


### Sample project
[LibraryEvolutionTest.zip](https://github.com/Adyen/adyen-ios/files/14054744/LibraryEvolutionTest.zip)

**Comment by ffittschen** [comment]
Please correct me if I'm wrong, but looking at the original PR that introduced the `@_spi` usage, it looks to me like it is only used to hide types from the DocC documentation. Since Swift 5.8, there is a [@_documentation(visibility:)](https://github.com/apple/swift/blob/main/docs/ReferenceGuides/UnderscoredAttributes.md#_documentationvisibility-) annotation, which was introduced specifically for this purpose. 

Maybe it would make sense to migrate from `@_spi` to `@_documentation(visibility: internal)`? That would most likely also eliminate the need to provide default implementations the compiler complained about when compiling `@_spi` annotated code with library evolution.

**Comment by goergisn** [comment]
Hi @ffittschen
Thank you for sharing + providing a sample project.

`@_spi` is used in our case to have visibility/accessibility of the specific objects within the SDK parts (Core, Session, Card, Components, ...) but not exposing them to the public interface. The reason for that is to not imply stability of these parts of the code (meaning not having to introduce breaking changes if any of these interfaces change).

I'm taking a look at it and keep you posted.

**Comment by ffittschen** [comment]
Ahh I see, maybe in that scenario the [`package`](https://github.com/apple/swift-evolution/blob/main/proposals/0386-package-access-modifier.md) access modifier introduced in Swift 5.9 would help to explicitly remove those SDK parts from the public interface instead of hiding them through SPI groups, while still being able to access them within the SPM package?

**Comment by goergisn** [comment]
Yes, we're currently exploring the scope of switching to the `package` access level as we also use `@_spi` on protocol properties/methods which don't allow individual access control and might require some more thought/work.

**Comment by goergisn** [comment]
Good afternoon @ffittschen,

It has been some time but we ~~might~~ have fixed the issue that you were running into.
I just ran the command on the [PR](https://github.com/Adyen/adyen-ios/pull/1834) that is currently in review. 
It would be great if you could try and confirm that this is solving your case.

https://github.com/Adyen/adyen-ios/pull/1834

We're also wondering if you're looking into creating one binary for multiple modules (e.g. `AdyenDropIn` + `AdyenSession`) or one binary per module? 
We noticed that when combining multiple libraries into one binary framework you can't have the module named after an object inside of that module (e.g. module `AdyenSession` fails to build because of `class AdyenSession`) - this is not an issue if it's a binary per module.

**Comment by ffittschen** [comment]
Hi @goergisn,

we worked around the issue by inverting the dependencies. Instead of having a Swift Package that depends on Adyen, our package now defines protocols, which we conform to in the app target by forwarding the method calls to the Adyen SDK. This way we don't create XCFrameworks of the Adyen targets anymore, we link them directly to the app target.

Unfortunately, this means that we can't confirm if the fix is working in our project, as our setup is different now. I did test it with the `archive.sh` script and sample project, which I provided above. That script succeeds on the PR and fails on the develop branch. So it seems like it is fixed 🥳

**Comment by goergisn** [comment]
Thanks again @ffittschen for the info and reporting in the first place.

We also took inspiration from your sample project and created a github workflow now ensures support for library evolution from now onwards. 👌

Will leave the ticket open until it's merged.

**Comment by goergisn** [comment]
FYI the [latest release (5.12.0)](https://github.com/Adyen/adyen-ios/releases/tag/5.12.0) contains your requested change 👌 
Will close the ticket but feel free to re-open / create a new one if there are any open questions/issues
