### ISSUE TITLE
[BUG] TWINT Apps cannot be opened when adding payment method (Fatal error/Crash)

### ISSUE THREAD

**Issue by ast3150** [Adyen/adyen-ios#1902]
**Describe the bug**
When trying to register TWINT as a payment method, the application crashes with a fatal error:
```
Fatal error: NSArray element failed to match the Swift Array Element type
Expected TWAppConfiguration but found TWAppConfiguration
```

**To Reproduce**
1. Build app with Ayen TWINT Native integration
2. Click on 'Add payment method'
3. Choose TWINT as payment method
4. Application crashes with fatal error

**Expected behavior**
The application does not crash and the selection which TWINT app should be opened is presented.

**Screenshots**
n/a

**Environment**
 - Device: iPhone 16 Pro
 - iOS Version: **iOS 18.1**
 - SDK Version: 5.13.0
 - Adyen API Version: unknown
 - Package management system: SPM
 - Xcode version: **16.1** (16B40)
 - Mac OS type: M1 Max

**Relevant source code**
File/Line: `TwintSDKActionComponent.swift:105`
Method: `public func handle(_ action: TwintSDKAction)`
Line: `guard let firstApp = installedApps.first else { `

**Additional context**
- Twint apps are configured with LSApplicationQueriesSchemes and integration is made as documented in `AdyenTwint.md`

**Comment by atmamont** [comment]
Thanks for reporting @ast3150! 

Could you provide additionally the following:
- full crash stack trace
- how you import Twint SDK framework (a screenshot of Xcode **General -> Frameworks, Libraries and Embedded content** settings might give us something)

TWINT test environment doesn't support iOS18 at the moment so we have limited means for investigation, just to set expectations it might take some time to sort it out.

**Comment by ast3150** [comment]
Sure, here you go.
[FELFEL-2024-11-20-182701.ips.zip](https://github.com/user-attachments/files/17834736/FELFEL-2024-11-20-182701.ips.zip)

We import the Adyen and AdyenTwint library through Swift Package Manager. Both are added to the "Frameworks, Libraries and Embedded Content" section as normal libraries.
![Screenshot 2024-11-20 at 18 33 19](https://github.com/user-attachments/assets/faee3a35-ccd7-407f-9b4f-d53499ce8c0b)

Please note that after reinstalling the library and app, I am currently no longer able to reproduce a crash. However, there is also no progress after choosing the payment method:

![Screenshot 2024-11-20 at 18 49 21](https://github.com/user-attachments/assets/cb9403f0-4ace-4987-a8e6-bd0656aa7915)

**Comment by atmamont** [comment]
Thanks for logs provided, it helps to narrow down the root cause.

As long as we cannot reproduce the crash, we can only have assumptions:
- is this the first time you integrate Twint or this crash occured after upgrading Adyen SDK to 5.13.0?
- Any chance you have `TwintSDK` imported  along with `AdyenTwint`? It is not necessary as AdyenTwint uses TwintSDK.
- Regarding the last screenshot with the `No such process found` error. Is this a chunk of logs that are filtered? Did you try to look for non-error messages? 
- TWINT SDK version that we use now doesn't support iOS18 properly and the testing infra is not ready yet from TWINT side. We cannot release new SDK version fully compatible with iOS18 until we test everything on our side. We are in full contact with TWINT team to speed up the process. This is a known issue and [was reported](https://github.com/Adyen/adyen-ios/issues/1783#issuecomment-2404269260) before.

**Comment by nauaros** [comment]
Hi @ast3150! 

Taking over @atmamont here.

We’ve created a new branch (#1905) where the `TwintSDK` has been updated to version 8.0.2.

This update resolves the compatibility issue with iOS 18 caused by the deprecated `openURL(_:)` method.

However, due to limitations in Twint’s ability to provide a complete TEST environment, we have not been able to fully test the entire Twint payment flow. That said, we have successfully verified that the app-to-app switch functionality works with this update.

We encourage you to try out this branch in the meantime while we continue working on verifying the full flow. Once the changes are thoroughly tested, we’ll include them in an official release.

We apologize for any inconvenience caused by these third-party dependencies. If you encounter any issues, please let us know. Thank you for your understanding and cooperation!

**Disclaimer:** Be aware this is not part of an official release, so keep in mind there can potentially be issues with the update that's why we encourage you to run test to make sure the whole Twint payment flow works as expected on iOS 18.

**Comment by ast3150** [comment]
Hi there. To answer the stuff above:
> is this the first time you integrate Twint or this crash occured after upgrading Adyen SDK to 5.13.0?

no, we have integrated Adyen before, but we're switching from the web-based flow to Adyen-twint-native now.

> Any chance you have TwintSDK imported along with AdyenTwint? It is not necessary as AdyenTwint uses TwintSDK.

no, we don't use Twint SDK directly, only through Adyen

> Regarding the last screenshot with the No such process found error. Is this a chunk of logs that are filtered? Did you try to look for non-error messages?

I didn't see any relevant non-error messages.

We'll try out the provided feature branch, thanks!

**Comment by nauaros** [comment]
Hi @ast3150 

Just wanted to let you know that we have been able to test the new update. Everything works fine and it will be included in our next release (v5.14.0) in the coming week. Thank you!

P.S. We will keep this issue opened for now in case you wanna provide any feedback. By the time we release, we will close it.

**Comment by goergisn** [comment]
Hi @ast3150 

We just shipped [5.14.0](https://github.com/Adyen/adyen-ios/releases/tag/5.14.0) which uses the latest version provided by Twint. This should resolve your issue.

I'm closing the issue but feel free to re-open if there are any additional questions. :)

**Comment by elitalon** [comment]
@goergisn I just tried [5.14.0](https://github.com/Adyen/adyen-ios/releases/tag/5.14.0) and I'm experiencing the same crash. Here are the details of our integration:

**Environment**
 - Device: iPhone SE 2nd Generation
 - iOS Version: 18.2
 - SDK Version: 5.14.0
 - Adyen API Version: 71
 - Package management system: SPM
 - Xcode version: 16.1 (16B40)
 - Mac OS type: M3

**Relevant source code**
[`TwintSDKActionComponent.handle(_:)`](https://github.com/Adyen/adyen-ios/blob/cc78c30daa3c1aa25f57ebe8850eb80c96c132ba/AdyenActions/Components/SDK/TwintSDKActionComponent.swift#L110), at [line 115](https://github.com/Adyen/adyen-ios/blob/cc78c30daa3c1aa25f57ebe8850eb80c96c132ba/AdyenActions/Components/SDK/TwintSDKActionComponent.swift#L115).

**Additional context**
- I only have one TWINT app installed: PostFinance TWINT
- `maxIssuerNumber` is set to the default value (`.max`)
- URL schemes in `LSApplicationQueriesSchemes` are set from `twint-issuer1` to `twint-issuer44` only (we don't have more space 😓)
- At the moment when the exception is thrown in `TwintSDKActionComponent.handle(_:)`, the `installedApps` parameter of the closure only contains one value (see screenshot below)

![nsarray_type_mismatch](https://github.com/user-attachments/assets/6590b7b7-d9a8-435a-9e96-b9e31813c20e)

We also get this message in the console at launch time when dylib3 is resolving symbols, which makes sense because our app also integrates the Datatrans SDK:

```
objc[7220]: Class TWAppConfiguration is implemented in both /private/var/containers/Bundle/Application/0ABCBE97-42AD-4403-B69C-0C154C92ED66/<redacted>/Frameworks/Datatrans.framework/Datatrans (0x10463e3f0) and /private/var/containers/Bundle/Application/0ABCBE97-42AD-4403-B69C-0C154C92ED66/<redacted>/Frameworks/TwintSDK.framework/TwintSDK (0x1026de250). One of the two will be used. Which one is undefined.
```

Do you have a hint as to how we can overcome that?

**Comment by goergisn** [comment]
Hi @elitalon 
We just tried to reproduce the crash but we didn't manage to (iOS 18.2, iPhone 14 Pro, one Twint app installed)

- Do you know which version of the Twint SDK the `Datatrans SDK` is using? There might be a mismatch.
- Is there a way you can try it without having `Datatrans SDK`?

**Comment by elitalon** [comment]
@goergisn Let's see if I can make a test without Datatrans SDK and gather that information for you. I'll let you know once I have more details.

**Comment by elitalon** [comment]
@goergisn After removing the Datatrans SDK, I don't have the crash anymore.

Now the registration fails on the TWINT app side with an "Invalid code" error. But I think that's because I'm using the Test environment with the production app. So let's leave that aside for now.

Unfortunately, I couldn't find a trace of the Twint SDK Datatrans is using. I have [reported](https://github.com/datatrans/ios-sdk/issues/19) the issue on their side.

In the meantime, do you see a way for us to move forward?

**Comment by goergisn** [comment]
Hi @elitalon 
I managed to reproduce it by including the Datatrans SDK

Currently looking into what we can do about it, but it seems that Datatrans and Adyen ship the TwintSDK and thus there is a naming collision caused with TWAppConfiguration.

I'll keep you posted.

**Comment by goergisn** [comment]
Hi @elitalon 
I updated the branch from https://github.com/Adyen/adyen-ios/pull/1913 to use the Statically linked `TwintSDK` which seems to resolves the issue.

Could you give it a try? (Make sure to reset your package caches)

**Comment by elitalon** [comment]
@goergisn Unfortunately I'm still facing the same crash 😕

Datatrans [provided](https://github.com/datatrans/ios-sdk/issues/19#issuecomment-2527514445) a couple of alternatives besides using a static framework, but I'm not sure how viable they're on your side.

**Comment by goergisn** [comment]
Hi @elitalon, just to double check:
 
### 1. Can you use `Update Package` 
(We noticed that reset package caches does not work reliably when the target is a branch and not a version)

<img width="407" alt="Screenshot 2024-12-09 at 15 45 16" src="https://github.com/user-attachments/assets/192174be-6863-4951-b593-08f0017b93a7">

### 2. ... and make sure that the path actually changes inside of the Package.swift file of the Adyen SDK dependency?

<img width="906" alt="Screenshot 2024-12-09 at 15 44 20" src="https://github.com/user-attachments/assets/d3d70032-b89b-489d-9535-600498b74acc">

On our side this fixes the reproducible issue when using Datatrans + Adyen via SPM.

**Comment by elitalon** [comment]
Hi @goergisn,

I can confirm that on our side we have the same setup, both for the custom branch in SPM:

![custom_branch](https://github.com/user-attachments/assets/19d60b91-a125-465c-9eb4-f39fe20ee2da)

As well as the entry in the package manifesto:

![static_package](https://github.com/user-attachments/assets/e257d1a3-c010-4a3c-b8c1-43ecaf5d5f68)

Note that we are also including `AdyenTwint` in the list of linked frameworks:

![linking_frameworks](https://github.com/user-attachments/assets/5c729d15-dc6c-419a-8fb5-a4f78d4693f8)

If I remove that, the crash is gone. But then we are back to square one with the web-based interface of the drop-in:

<img src="https://github.com/user-attachments/assets/e92f3b38-3025-48cc-a338-fab73e1d4c24" width="33%" />

**Comment by nauaros** [comment]
Hi there!

Closing this issue as the fix has been released on [v5.15.0](https://github.com/Adyen/adyen-ios/releases/tag/5.15.0). Feel free to reopen if the problem remains.

Thanks!
